// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import type { RateLimiter } from '@cloudflare/workers-types'; // Import the type

interface Env {
	_3R60S: RateLimiter; // Add the binding type
}
