name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: "main"
    paths:
      - 'web/**'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data
        uses: actions/checkout@v4
        with:
          ref: data
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run import script
        run: |
          git worktree add hetzner-sb data
          poetry run python scripts/import.py hetzner-sb web/static/sb.duckdb.wasm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          #cache: npm

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: build
        working-directory: ./web
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: "web/build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4